### ISSUE TITLE
What about a README to use this project?

### ISSUE THREAD

**Issue by mbaechler** [henrybear327/Proton-API-Bridge#1]
Hi,
I just discovered your effort to bring rclone to Proton Drive and it's awesome, thank you for that.
It looks like it should be in a working state if your TODO list is trustworthy, would you mind writing a short manual to let me (and others) use rclone on Proton?

**Comment by henrybear327** [comment]
Hello @mbaechler,

Thanks for reaching out! 

The effort is already underway [here](https://github.com/rclone/rclone/pull/7093) and should be merged soon. 

Do you have any specific requests?

Thank you!

Henry

**Comment by mbaechler** [comment]
Thanks Henry, I will subscribe to the linked issue.

**Comment by henrybear327** [comment]
No worries :) 

> I just discovered your effort to bring rclone to Proton Drive

Just curious, how did you find this project out of nowhere :D, and if there is a specific README that you would like to see? (Currently, this library is just to make rclone easy to talk to the proton API as there is heavy encryption around it. It's now finally in a state that is stable, so I will clean up the code when I finish my thesis in a month or so)
