### ISSUE TITLE
Fix "No matching signature" bug 

### ISSUE THREAD

**Issue by henrybear327** [henrybear327/Proton-API-Bridge#3]
See [issue](https://github.com/rclone/rclone/issues/6072#issuecomment-1663529482)

**Comment by henrybear327** [comment]
Due to primary email switching, the signing key might not be the one listed in the main share's metadata, but instead, we need to use the email listed in the node's property.

**Comment by Erik1000** [comment]
Does this account for the same email address switching its key?

**Comment by henrybear327** [comment]
> Does this account for the same email address switching its key?

If an email address has several keys, as long as it can be decrypted, it will be loaded onto the keyring for signature verification, if I am not mistaken. So yes, it should have been accounted for. 

(sorry that I just realized I had a typo in the previous message... @Erik1000. It should say primary email instead of primary key)

**Comment by AimVaguely** [comment]
@henrybear327 is this the issue for fixing the "root cause" that you mentioned [here](https://github.com/rclone/rclone/pull/7203#issuecomment-1699423782) to make the workaround for SkipSignatureVerifications not needed?

**Comment by henrybear327** [comment]
> @henrybear327 is this the issue for fixing the "root cause" that you mentioned [here](https://github.com/rclone/rclone/pull/7203#issuecomment-1699423782) to make the workaround for SkipSignatureVerifications not needed?

Hello @AimVaguely, 

Yes, it is.

**Comment by AimVaguely** [comment]
> > @henrybear327 is this the issue for fixing the "root cause" that you mentioned [here](https://github.com/rclone/rclone/pull/7203#issuecomment-1699423782) to make the workaround for SkipSignatureVerifications not needed?
> 
> Hello @AimVaguely,
> 
> Yes, it is.

Please tell me if I can do anything to help with solving this issue. I am still encountering it currently, and the only way to use rsync with my proton is to use the build that you gave me previously. So if there are any logs, or testing that I can help with, please tell me.

**Comment by henrybear327** [comment]
> > > @henrybear327 is this the issue for fixing the "root cause" that you mentioned [here](https://github.com/rclone/rclone/pull/7203#issuecomment-1699423782) to make the workaround for SkipSignatureVerifications not needed?
> > 
> > 
> > Hello @AimVaguely,
> > Yes, it is.
> 
> Please tell me if I can do anything to help with solving this issue. I am still encountering it currently, and the only way to use rsync with my proton is to use the build that you gave me previously. So if there are any logs, or testing that I can help with, please tell me.

Hello @AimVaguely, 

I will be finishing my thesis defense tomorrow, and then I will quickly patch up the pending issues, especially this one!!

Sorry for making you wait, I will fix this issue and tag you ASAP after I am done with my defense!

Thanks again for all the debugging help!!

Henry

**Comment by AimVaguely** [comment]
> > > > @henrybear327 is this the issue for fixing the "root cause" that you mentioned [here](https://github.com/rclone/rclone/pull/7203#issuecomment-1699423782) to make the workaround for SkipSignatureVerifications not needed?
> > > 
> > > 
> > > Hello @AimVaguely,
> > > Yes, it is.
> > 
> > 
> > Please tell me if I can do anything to help with solving this issue. I am still encountering it currently, and the only way to use rsync with my proton is to use the build that you gave me previously. So if there are any logs, or testing that I can help with, please tell me.
> 
> Hello @AimVaguely,
> 
> I will be finishing my thesis defense tomorrow, and then I will quickly patch up the pending issues, especially this one!!
> 
> Sorry for making you wait, I will fix this issue and tag you ASAP after I am done with my defense!
> 
> Thanks again for all the debugging help!!
> 
> Henry

Thanks!

Take all the time you need. I was just making sure that I was in the correct spot and checking if I can help. Thank you for all the remarkable work you have done on this so far. 

My current setup works currently, so don't rush. I am just using the build you gave me previously.

**Comment by henrybear327** [comment]
Hello @AimVaguely, 

Can you try to pull from this branch https://github.com/rclone/rclone/pull/7278, and then run `make` at the top-level folder so the `rclone` with the latest changes will be compiled? After that, you should be able to try out the latest signature verification code!

Please let me know if it works for you or not. If not, I will probably make a special version for you, which I will aggressively dump out the file/folder's associated email address (no sensitive information such as private keys will be dumped) so I can figure out what's the secret sauce behind this weird signature verification bug...

Thank you!

**Comment by AimVaguely** [comment]
> Hello @AimVaguely,
> 
> Can you try to pull from this branch [rclone/rclone#7278](https://github.com/rclone/rclone/pull/7278), and then run `make` at the top-level folder so the `rclone` with the latest changes will be compiled? After that, you should be able to try out the latest signature verification code!
> 
> Please let me know if it works for you or not. If not, I will probably make a special version for you, which I will aggressively dump out the file/folder's associated email address (no sensitive information such as private keys will be dumped) so I can figure out what's the secret sauce behind this weird signature verification bug...
> 
> Thank you!

Thanks, @henrybear327. I have done so and replied to the pull request you linked. If you put together the version with more logging, I would be happy to run it, so you can get additional information. If I can help with adding a break point at any point in the code and reading variables, I also am experienced in doing that (I don't have much experience in go debugging, but VS Code exposes it in a way I am experienced in).

**Comment by AimVaguely** [comment]
> Hello @AimVaguely,
> 
> Can you try to pull from this branch [rclone/rclone#7278](https://github.com/rclone/rclone/pull/7278), and then run `make` at the top-level folder so the `rclone` with the latest changes will be compiled? After that, you should be able to try out the latest signature verification code!
> 
> Please let me know if it works for you or not. If not, I will probably make a special version for you, which I will aggressively dump out the file/folder's associated email address (no sensitive information such as private keys will be dumped) so I can figure out what's the secret sauce behind this weird signature verification bug...
> 
> Thank you!

Thanks, @henrybear327. I have done so and replied to the pull request you linked. If you put together the version with more logging, I would be happy to run it, so you can get additional information. If I can help with adding a break point at any point in the code and reading variables, I also am experienced in doing that (I don't have much experience in go debugging, but VS Code exposes it in a way I am experienced in).

This message was meant to be sent a while ago, directly after I made my other comment. But I forgot to press send.

**Comment by henrybear327** [comment]
> > Hello @AimVaguely,
> > Can you try to pull from this branch [rclone/rclone#7278](https://github.com/rclone/rclone/pull/7278), and then run `make` at the top-level folder so the `rclone` with the latest changes will be compiled? After that, you should be able to try out the latest signature verification code!
> > Please let me know if it works for you or not. If not, I will probably make a special version for you, which I will aggressively dump out the file/folder's associated email address (no sensitive information such as private keys will be dumped) so I can figure out what's the secret sauce behind this weird signature verification bug...
> > Thank you!
> 
> Thanks, @henrybear327. I have done so and replied to the pull request you linked. If you put together the version with more logging, I would be happy to run it, so you can get additional information. If I can help with adding a break point at any point in the code and reading variables, I also am experienced in doing that (I don't have much experience in go debugging, but VS Code exposes it in a way I am experienced in).
> 
> This message was meant to be sent a while ago, directly after I made my other comment. But I forgot to press send.

Hello @AimVaguely, 

Thanks for all the help that you have offered!

In the end, it's more about adding in all the potential cases where the signature might have been signed before, so I didn't get to the phase where I would need your help on adding breakpoints!

Henry
